yolo_model:

  config_file:
    name: yolov3-tiny-car-license.cfg
  weight_file:
    name: yolov3-tiny-car-license_final.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - car-license-plate
